---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: kubernetes-bootcamp
 spec:
   replicas: 2
   template:
     spec:
       containers:
         - name: kubernetes-bootcamp
           image: gcr.io/google-samples/kubernetes-bootcamp:v1
           ports:
             - containerPort: 8080
